commonLabels:
  cluster.x-k8s.io/v1beta1: v1beta1

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_scalewayclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_scalewaymachines.yaml
- bases/infrastructure.cluster.x-k8s.io_scalewayclustertemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_scalewaymachinetemplates.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_scalewayclusters.yaml
#- path: patches/webhook_in_scalewaymachines.yaml
#- path: patches/webhook_in_scalewayclustertemplates.yaml
#- path: patches/webhook_in_scalewaymachinetemplates.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_scalewayclusters.yaml
#- path: patches/cainjection_in_scalewaymachines.yaml
#- path: patches/cainjection_in_scalewayclustertemplates.yaml
#- path: patches/cainjection_in_scalewaymachinetemplates.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
